[package]
name = "spotify-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librespot = { version = "0.4.2" }
tokio = "1.11.0"
serenity = "0.11.5"
songbird = "0.3.0"
